### ISSUE TITLE
同一个文件嵌套注解，build报错

### ISSUE THREAD

**Issue by c4jeff** [debuggerx01/platform_code_builder_starter#1]
> RangeError (end): Invalid value: Not in inclusive range 291..345: 415

示例代码：
```dart
@PlatformDetector()
import 'package:flutter/material.dart';
import 'package:platform_code_builder/platform_code_builder.dart';

@PlatformSpec(platformType: PlatformType.desktop)
class Test01 {
  @PlatformSpec(platformType: PlatformType.mac)
  getContainer() {
    return Container();
  }

  @PlatformSpec(platformType: PlatformType.linux, renameTo: "getContainer")
  getContainerTest() {
    return Container();
  }
}

@PlatformSpec(platformType: PlatformType.android, renameTo: "Test01")
class Test02 {
  @PlatformSpec(platformType: PlatformType.vivo)
  getContainer() {
    return Container();
  }

  @PlatformSpec(platformType: PlatformType.xiaomi, renameTo: "getContainer")
  getContainerTest() {
    return Container();
  }
}
```

**Comment by debuggerx01** [comment]
> > RangeError (end): Invalid value: Not in inclusive range 291..345: 415
> 
> 示例代码：
> 
> ```dart
> @PlatformDetector()
> import 'package:flutter/material.dart';
> import 'package:platform_code_builder/platform_code_builder.dart';
> 
> @PlatformSpec(platformType: PlatformType.desktop)
> class Test01 {
>   @PlatformSpec(platformType: PlatformType.mac)
>   getContainer() {
>     return Container();
>   }
> 
>   @PlatformSpec(platformType: PlatformType.linux, renameTo: "getContainer")
>   getContainerTest() {
>     return Container();
>   }
> }
> 
> @PlatformSpec(platformType: PlatformType.android, renameTo: "Test01")
> class Test02 {
>   @PlatformSpec(platformType: PlatformType.vivo)
>   getContainer() {
>     return Container();
>   }
> 
>   @PlatformSpec(platformType: PlatformType.xiaomi, renameTo: "getContainer")
>   getContainerTest() {
>     return Container();
>   }
> }
> ```

之前没考虑到这种情况，外层代码块已经被整个移除的情况下应该忽略内部的处理。
加了点判断处理了这种情况，谢谢反馈。
